#!/usr/bin/env node
/**
 * Renders the case view in REAL Chrome over fixture reports and measures it.
 *
 * Rebuilt 2026-09-01 with the rest of web-auth/. Zero dependencies on purpose: the web
 * image has no build step and this repo has no node_modules, so the harness talks the
 * DevTools protocol directly over Node's built-in WebSocket. That is also why the
 * original never needed puppeteer.
 *
 * What it is for. The rail is generated by string concatenation from a JSONB blob whose
 * shape has changed six times. Nothing else catches a metric that renders `NaN`, a
 * column that overflows at 640 px, a panel that appears for a job that cannot support
 * it, or -- the one that matters most here -- an absolute Hounsfield number leaking into
 * copy that must never carry one.
 *
 * Every assertion must be PROVEN to fail when the thing it guards is broken. That is
 * this project's standing rule and it exists because the last plan-tab assertion was
 * written vacuously, referenced a variable that did not exist, and passed anyway.
 * `--prove` runs that proof.
 */
import http from 'node:http';
import { spawn } from 'node:child_process';
import { readFileSync, readdirSync, existsSync, mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(HERE, '..');
const WEB = path.join(ROOT, 'web');
const FIX = path.join(HERE, 'fixtures');

// 1100 and 1180 sit in the band between the 1000 px stacking breakpoint and a
// comfortable desktop, which nothing covered -- and that is exactly where the plan
// stage's rail + sidebar minimums collided and pushed the page 36 px sideways.
//
// 1470 is the user's own logical width and nothing above 1440 was tested; 1010 is the
// tightest two-column state, one pixel band above the stacking breakpoint. Both were
// added when a re-measurement showed the section is WIDTH-bound (gutter 0) from 1180
// down and HEIGHT-bound above it -- two different regimes that no single width sees.
const WIDTHS = [1470, 1440, 1280, 1180, 1100, 1024, 820, 640];

// Height matters now that the plan stage's vertical budget is the binding constraint
// on the cross-section. 836 is the user's real inner height on a 900-tall screen.
const HEIGHTS = [900, 836];
const PORT_WAIT_MS = Number(process.env.CHECK_RAIL_PORT_WAIT_MS || 45000);

// Expected counts per fixture. `0` entries are the point: they assert that a job with
// no accuracy block and no planning pack renders EXACTLY as it did before those
// features existed. An absence that is merely untested is an absence that regresses.
const EXPECT = {
  'report-37-threemodel': { dice: 0, plan: 0, accuracy: 0 },
  'report-47-example':    { dice: 0, plan: 0, accuracy: 0 },
  'report-47-older':      { dice: 0, plan: 0, accuracy: 0 },
  'report-47-tf3':        { dice: 0, plan: 0, accuracy: 0 },
  'report-47-accuracy':   { dice: '>0', plan: 0, accuracy: 1 },
  'report-47-planning':   { dice: 0, plan: 1, accuracy: 0 },
};

// Bone-quality claims, forbidden ANYWHERE. A Misch class or a "D2 bone" is a statement
// about density derived from absolute attenuation, and CBCT has none to derive it from:
// `worker/tf3.calibrate` measures gains from 0.47 to 2.60 across real scans, so the same
// trabecular bone reads as a different number on a different machine. Everything this
// product says about density is a RATIO for that reason.
const FORBIDDEN_ANYWHERE = /Misch|\bD[1-4]\b|bone quality|bone density of/i;

// Absolute Hounsfield figures, forbidden in the MEASUREMENT surface specifically.
// They are legitimate elsewhere and the rail already uses them well -- "Grey values:
// not calibrated HU" is the disclaimer, and the intensity card reports the air and
// soft-tissue landmarks the calibration actually measured. What must never happen is a
// millimetre-or-density readout quoting an absolute number as if it meant something.
const FORBIDDEN_IN_MEASUREMENT = /\bHU\b|Hounsfield/i;

// ...and the disclaimer is asserted POSITIVELY rather than merely permitted, because
// its absence is the failure that matters. Deleting it would otherwise pass every check.
const REQUIRED_DISCLAIMER = /not calibrated/i;
const BAD_TOKENS = /\bNaN\b|\bundefined\b|\bInfinity\b|\[object Object\]|\bnull\b/;

// Ceilings on the per-implant card. Measured on the live site before this block: ONE
// implant produced 2745 characters in a 1118 px card, and 65% of the sidebar was
// scrolled out of reach with no way to know it. These are budgets, not targets --
// they exist so the panel cannot quietly grow back.
// Neither is a round number.
//
// A card with every row collapsed measures ~270 px, and the sidebar is 657 px on the
// user's window, so two of those fit without scrolling -- which is the goal. Each row
// that is FORCE-OPEN adds ~78 px, and rows are forced open exactly when they are
// ungraded or carry a caveat. That is not padding to squeeze out: a refusal a reader
// can skim past is the one thing this panel must not produce. The fixture is a
// deliberate worst case (i1 has a caveated tooth row, i2 has an ungraded canal AND a
// caveated tooth), so 360 is base + two forced rows with a little slack.
//
// The baseline these replace, measured on the live site with ONE implant: 1118 px and
// 2745 characters, with 65% of the sidebar unreachable and no scrollbar to say so.
const IMP_CARD_MAX_PX = 360;
const IMP_CARD_MAX_CHARS = 400;

// openCase must not throw AT ALL. It used to sit behind a bare
// `catch (e) { /* mountVolume needs a GPU */ }`, which measurement showed was
// catching nothing: openCaseError came back null in all 60 states. So the comment was
// stale and the catch was blinding the harness for free -- a null deref in renderArch,
// a broken download list or a throw in the plan panel would all have been reported as
// ALL PASS. If a genuine GPU-mount failure ever does surface here, add it to this
// pattern deliberately rather than widening the catch.
const EXPECTED_MOUNT_FAILURE = /$^/;   // matches nothing: no failure is expected

// ------------------------------------------------------------------ plumbing
function serve(dir) {
  const types = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css',
                  '.json': 'application/json', '.jpg': 'image/jpeg', '.png': 'image/png' };
  const srv = http.createServer((req, res) => {
    const rel = decodeURIComponent(req.url.split('?')[0]);
    // selftest.html fetches the golden vectors, which live with the Python tests that
    // generate them rather than in the shipped web root.
    // Fixture pictures. The plan tab is made of two canvases and until these existed
    // the harness had never rendered one, never called planCtx, and therefore could not
    // see a transform, a crop or an annotation defect at all.
    const p = rel === '/plan_vectors.json'
      ? path.join(ROOT, 'tests/plan_vectors.json')
      : rel.startsWith('/__fixtures/')
        ? path.join(FIX, 'assets', rel.slice('/__fixtures/'.length))
        : path.join(dir, rel === '/' ? '/index.html' : rel);
    const roots = [dir, path.join(ROOT, 'tests'), path.join(FIX, 'assets')];
    if (!existsSync(p) || !roots.some((r) => p.startsWith(r))) {
      res.writeHead(404).end('no'); return;
    }
    res.writeHead(200, { 'content-type': types[path.extname(p)] || 'application/octet-stream' });
    res.end(readFileSync(p));
  });
  return new Promise((ok) => srv.listen(0, '127.0.0.1', () => ok({ srv, port: srv.address().port })));
}

async function cdp(debugPort) {
  const deadline = Date.now() + PORT_WAIT_MS;
  let info;
  // Chrome is slow to write DevToolsActivePort on a loaded box; the old budget was
  // 20 s and reported that as "no DevTools port" on a machine that was merely busy.
  for (;;) {
    try { info = await (await fetch(`http://127.0.0.1:${debugPort}/json/version`)).json(); break; }
    catch { if (Date.now() > deadline) throw new Error('no DevTools port'); await new Promise((r) => setTimeout(r, 200)); }
  }
  const ws = new WebSocket(info.webSocketDebuggerUrl);
  await new Promise((ok, no) => { ws.onopen = ok; ws.onerror = () => no(new Error('cdp connect failed')); });
  let id = 0; const waiting = new Map(); const events = new Map();
  ws.onmessage = (m) => {
    const msg = JSON.parse(m.data);
    if (msg.id && waiting.has(msg.id)) {
      const { ok, no } = waiting.get(msg.id); waiting.delete(msg.id);
      msg.error ? no(new Error(JSON.stringify(msg.error))) : ok(msg.result);
    } else if (msg.method && events.has(msg.method)) {
      events.get(msg.method).forEach((f) => f(msg.params)); events.delete(msg.method);
    }
  };
  const send = (method, params = {}, sessionId) => new Promise((ok, no) => {
    id += 1; waiting.set(id, { ok, no });
    ws.send(JSON.stringify({ id, method, params, ...(sessionId ? { sessionId } : {}) }));
  });
  const once = (method) => new Promise((ok) => {
    if (!events.has(method)) events.set(method, []);
    events.get(method).push(ok);
  });
  return { send, once, close: () => ws.close() };
}

// -------------------------------------------------------- the in-page probe
// Runs inside Chrome. Drives the REAL openCase() against a stubbed fetch rather than
// calling render functions one by one, so what is measured is the path a user takes.
const ARCH = JSON.parse(readFileSync(path.join(FIX, 'assets/arch-mandible.json'), 'utf8'));
// A REAL /measure reply, generated by `scripts/make_web_fixtures.py` from the real
// `plan_metrics` + `plan_safety` against a real pack, so the headline wording, the
// `numbers` keys and the `because` lists cannot drift from what the server sends. The
// old stub was `{implants: [], priors: {}}`, which meant the probe never reached a
// clearance block, a headroom bar or a verdict chip -- and `priors.by_structure` being
// undefined would have thrown on the first paint of anything that reads it.
//
// It deliberately covers every verdict state at once: i1's canal is `clear`, its tooth
// is `no_verdict` (a negative value with a caveat), its accessory canal is a SATURATED
// bound with a null value; i2's canal is `no_verdict`; and the pair is a `breach`.
const MEASURE = JSON.parse(readFileSync(path.join(FIX, 'assets/measure-mandible.json'), 'utf8'));

const PROBE = (fixture, fold, arch, measure) => `(async () => {
  window.DENTISTRY_NO_BOOT = true;
  const REPORT = ${JSON.stringify(fixture)};
  const ARCH = ${JSON.stringify(arch)};
  const MEASURE = ${JSON.stringify(measure)};
  // A paint throw used to be INVISIBLE here. selectXs chains its .catch after its
  // .then, so a throw from drawRulers -> drawImplants landed in the load-failure
  // handler, was relabelled \'this cross-section could not be loaded\' and the harness
  // printed ALL PASS. Verified by patching a throw in. Captured both ways.
  const pageErrors = [];
  window.addEventListener('error', (e) => pageErrors.push('error:' + (e.message || e.type)));
  window.addEventListener('unhandledrejection',
    (e) => pageErrors.push('rejection:' + String((e.reason && e.reason.message) || e.reason)));
  const REAL_FETCH = window.fetch.bind(window);
  const JOB = { id: 'fixture', state: 'done', results_expired: false,
                title: 'Fixture case', filename: 'fixture.nii.gz',
                created_at: '2026-08-29T19:05:00Z', reports: REPORT };
  window.fetch = async (url) => {
    const u = String(url);
    // The plan tab fetches its manifest through the artifact endpoint; without it
    // the tab opens onto nothing and the ruler and implant panel are never exercised.
    if (u.includes('planning/arch.json')) {
      return new Response(JSON.stringify(ARCH), { status: 200,
        headers: { 'content-type': 'application/json' } });
    }
    if (u.includes('/measure')) {
      return new Response(JSON.stringify(MEASURE), { status: 200,
        headers: { 'content-type': 'application/json' } });
    }
    // The two plan pictures, served off the harness's own static root. Real bitmaps at
    // the real published sizes, because planCtx sizes the backing store from
    // naturalWidth/naturalHeight and the panoramic's 3.32x anisotropy correction is
    // read from pixel_mm -- a stub of the wrong size would make every transform
    // assertion agree with itself and with nothing else.
    // The 401/404 that blanked every planning picture in production for ten days. Set
    // by the --prove break; there is no other way to reach it, because the stub answers
    // whatever path the manifest names.
    // The structure outlines, re-keyed to the fixture's own section list by
    // 'scripts/make_web_fixtures.py'. Without these the plan tab renders its
    // "this case predates outlines" state at every measured state, and the drawn path
    // -- the one that has a units bug waiting in it -- is never exercised.
    if (u.includes('contours.json')) return REAL_FETCH('/__fixtures/contours-mandible.json');
    if (u.includes('planning/xs/')) {
      if (ARCH.__breakImages) return new Response('no', { status: 404 });
      return REAL_FETCH('/__fixtures/xs-mandible.jpg');
    }
    if (u.includes('planning/pan/')) return REAL_FETCH('/__fixtures/pan-mandible.jpg');
    const body = u.includes('/structures') ? { groups: REPORT.structures || [] }
      : u.includes('/jobs/') ? JOB
      : u.includes('/me') ? { plan: { name: 'Explorer' }, billingEnabled: false }
      : {};
    return new Response(JSON.stringify(body), { status: 200,
      headers: { 'content-type': 'application/json' } });
  };
  window.DentistryAuth = { init: async () => {}, isSignedIn: () => true,
    profile: () => ({ sub: 'u', email: 'x@y.z', username: 'x' }),
    token: async () => 't', signIn() {}, signOut() {} };
  state.catalog = { groups: REPORT.structures || [] };
  // openCase is expected to throw HERE and ONLY here: mountVolume needs a GPU and
  // this Chrome runs --disable-gpu. Swallowing every error blinded the harness --
  // a null deref in renderArch, renderDownloads or the plan panel would be reported
  // as ALL PASS. The message is returned so the assertion block can insist the
  // failure is the known one.
  let openCaseError = null;
  try { await openCase('fixture'); } catch (e) { openCaseError = String(e && (e.message || e)); }
  // route() normally reveals the workspace; openCase is called directly here so that
  // a failure in one render function is attributable, which means unhiding it by hand.
  for (const id of ['home', 'settings']) { const e = document.getElementById(id); if (e) e.hidden = true; }
  const ws = document.getElementById('workspace'); if (ws) ws.hidden = false;
  // The two <details> cards are the "folds": collapsed and expanded lay the rail out
  // differently and the expanded one is where the long model/provenance rows live.
  for (const id of ['seriesCard', 'runCard']) {
    const e = document.getElementById(id); if (e) e.open = ${fold ? "true" : "false"};
  }
  // Actually OPEN the plan tab when the job carries one. Asserting only that the tab
  // appears leaves the ruler, the section navigation and the implant panel untested.
  const planTab = document.getElementById('planTab');
  const planned = planTab && !planTab.hidden;
  if (planned) { setMode('plan'); await new Promise((r) => setTimeout(r, 320)); }
  // ACTUALLY PLACE IMPLANTS. Until this existed the harness had never drawn one, so
  // every assertion about the implant panel, the verdict chips, the headroom bars, the
  // section overlay and the coordinate map was vacuous by construction -- the panel was
  // empty at all 84 states and BAD_TOKENS was guarding an empty string.
  //
  // Ids matter: addImplant issues i1 then i2, and the MEASURE fixture is keyed on
  // exactly those, so the panel renders the real server reply rather than a blank.
  let implantsPlaced = 0;
  if (planned && typeof addImplant === 'function') {
    const info = ((state.viewer.plan.arch || {}).jaws || {}).mandible;
    const sites = (info && info.sites) || {};
    for (const fdi of ['46', '45']) {
      const st = sites[fdi];
      if (st && st.s_mm != null && addImplant(st.s_mm, Number(fdi))) implantsPlaced += 1;
    }
    await new Promise((r) => setTimeout(r, 320));
  }
  await new Promise((r) => setTimeout(r, 200));

  const rail = document.querySelector('.rail') || document.body;
  const vis = (el) => !!(el && el.offsetParent !== null && !el.hidden);
  // SVG children report scrollWidth/clientWidth against their own viewBox units, so the
  // FDI arch chart reads as "20 > 15" forever and means nothing. HTML elements only.
  const overflowing = [...rail.querySelectorAll('*')].filter(
    (e) => !(e instanceof SVGElement)
        && e.scrollWidth > e.clientWidth + 1
        && getComputedStyle(e).overflowX === 'visible')
    .map((e) => (e.className || e.tagName) + ':' + e.scrollWidth + '>' + e.clientWidth);
  const text = rail.innerText || '';
  const card = document.getElementById('accuracyCard');
  const planPanel = document.getElementById('planStage');
  const measurementText = [card, planPanel]
    .filter((e) => e && !e.hidden).map((e) => e.innerText || '').join(String.fromCharCode(10));
  // Readouts that live OUTSIDE the rail and were therefore guarded by nothing. On
  // 2026-09-01 worker/preview.py stopped emitting total_slices and #sliceLabel
  // rendered "axial 137 / undefined": BAD_TOKENS only ever saw rail text.
  // textContent, not innerText, so a readout inside a collapsed pane still counts --
  // the question is whether the string is wrong, not whether it is on screen.
  // NOTE: this whole function is the body of a template literal. No backticks.
  const chromeText = ['sliceLabel', 'xsLabel', 'xsMeta', 'planArcHint', 'planNotice']
    .map((id) => document.getElementById(id))
    .filter(Boolean).map((e) => e.textContent || '').join(String.fromCharCode(10));
  // How much of the wrap the picture actually PAINTS, and how much of the picture is
  // letterbox. 'planCanvasCrop' only asks whether the canvas overflows its wrap; it
  // cannot see a canvas that fits and paints 16% of the box, which is what the live
  // measurement found. Reported per canvas so the vertical program can be checked by
  // number rather than by eye.
  const paint = ['panCanvas', 'xsCanvas'].map((id) => {
    const cv = document.getElementById(id);
    const wrap = cv && cv.parentElement;
    if (!cv || !wrap || !cv.width || !cv.height) return null;
    const b = cv.getBoundingClientRect();
    const w = wrap.getBoundingClientRect();
    if (b.width < 1 || w.width < 1) return null;
    const k = Math.min(b.width / cv.width, b.height / cv.height);
    return { id, paintedW: Math.round(cv.width * k), paintedH: Math.round(cv.height * k),
             wrapW: Math.round(w.width), wrapH: Math.round(w.height),
             gutterX: Math.round((b.width - cv.width * k) / 2),
             fill: Math.round(100 * (cv.width * k * cv.height * k) / (w.width * w.height)) };
  }).filter(Boolean);

  // How many structures the section overlay actually drew, and whether they land ON
  // the picture. Re-run against the live manifest rather than trusting the draw call.
  let contoursDrawn = 0; let contoursInside = true; let contourBounds = '';
  try {
    const pp = state.viewer && state.viewer.plan;
    const inf = pp && ((pp.arch || {}).jaws || {})[pp.jaw];
    const store = pp && (pp.xsc || {})[pp.jaw];
    const sl = store && store.state === 'ok' && store.data && store.data[String(pp.index)];
    if (sl && inf) {
      const only = planKeySet();
      const W = inf.cross_sections.size[1]; const H = inf.cross_sections.size[0];
      let lo = [1e9, 1e9]; let hi = [-1e9, -1e9];
      Object.keys(sl).forEach((k) => {
        if (!only.has(Number(k))) return;
        if (state.viewer.hidden.has(Number(k))) return;
        contoursDrawn += 1;
        sl[k].forEach((ring) => ring.forEach(([row, col]) => {
          lo = [Math.min(lo[0], col), Math.min(lo[1], row)];
          hi = [Math.max(hi[0], col), Math.max(hi[1], row)];
        }));
      });
      if (contoursDrawn) {
        contoursInside = lo[0] >= -1 && lo[1] >= -1 && hi[0] <= W + 1 && hi[1] <= H + 1;
        contourBounds = Math.round(lo[0]) + ',' + Math.round(lo[1]) + ' .. '
          + Math.round(hi[0]) + ',' + Math.round(hi[1]) + ' in ' + W + 'x' + H;
      }
    }
  } catch (e) { contourBounds = 'probe threw: ' + e.message; contoursInside = false; }

  const cards = [...document.querySelectorAll('#implantPanel .imp')];
  const side = document.getElementById('planSide');

  return {
    text, measurementText, chromeText, openCaseError,
    pageErrors, implantsPlaced, paint, contoursDrawn, contoursInside, contourBounds,
    // The card that measured 1118 px tall and 2745 characters on the live site, with
    // 65% of the sidebar scrolled out of reach. Asserted as a number so it cannot
    // regress quietly.
    impHeights: cards.map((e) => Math.round(e.getBoundingClientRect().height)),
    // Text a reader actually sees, so the SELECT OPTIONS do not count. innerText walks
    // every <option> in a closed dropdown -- 40 characters per card of '3.3 3.75 4.1 6
    // 8 10 11.5 13' that is never on screen at once -- and counting them would make the
    // budget measure the catalogue rather than the prose.
    impChars: cards.map((e) => {
      // innerText, so a CLOSED disclosure does not count -- textContent would report
      // every collapsed row and make the budget measure the markup, not the reading.
      // The selects are hidden first and restored after, because innerText walks every
      // <option> in a closed dropdown: 40 characters per card of '3.3 3.75 4.1 6 8 10
      // 11.5 13' that is never on screen at once, i.e. the catalogue, not the prose.
      const sels = [...e.querySelectorAll('select')];
      sels.forEach((n) => { n.style.display = 'none'; });
      const n = (e.innerText || '').replace(/\s+/g, ' ').trim().length;
      sels.forEach((x) => { x.style.display = ''; });
      return n;
    }),
    sideScroll: side ? [side.scrollHeight, side.clientHeight] : null,
    // Every verdict the panel is showing, so a chip that renders no_verdict as clear --
    // or renders nothing at all -- is a FAIL rather than a silent pass.
    verdictWords: [...document.querySelectorAll('#implantPanel .verdict, #implantPanel .vchip')]
      .map((e) => (e.textContent || '').trim().slice(0, 40)),
    // textContent, not innerText: the disclaimer lives inside the run-details
    // <details>, which starts closed. Whether the user has opened it is not the
    // question -- whether the sentence still exists is.
    allText: rail.textContent || '',
    dice: rail.querySelectorAll('.dice').length,
    accuracy: vis(document.getElementById('accuracyCard')) ? 1 : 0,
    plan: vis(document.getElementById('planTab')) ? 1 : 0,
    rows: rail.querySelectorAll('.srow').length,
    planned: planned ? 1 : 0,
    implantPanel: document.getElementById('implantPanel')
      && document.getElementById('implantPanel').innerHTML.length > 0 ? 1 : 0,
    jawTabs: document.querySelectorAll('#planJawTabs .plane').length,
    jawDisabled: document.querySelectorAll('#planJawTabs .plane[disabled]').length,
    fov: rail.querySelectorAll('.fovmark').length,
    overflow: overflowing.slice(0, 4),
    bodyOverflowX: document.body.scrollWidth > window.innerWidth + 1,
    // Does a plan canvas fit inside the box that clips it?
    //
    // These two are the surfaces an implant is placed and angled on, and their wrap is
    // overflow:hidden, so a canvas larger than its wrap is not a visible layout error
    // -- it is a silent CROP. Measured on the live site at 0.12.0: a 480x906
    // cross-section canvas displayed at full size inside a 530x431 wrap, so more than
    // half of it was off screen and what remained read as a plausible picture of
    // something else. The cause was max-height:100% resolving against an implicit auto
    // grid row that had already grown to the canvas's own height, which makes the
    // constraint non-binding by construction and cost nothing until the backing store
    // was doubled for DPR.
    //
    // Compared against the WRAP, not the canvas's own rect, because that is the box
    // doing the clipping. 1 px of slack for subpixel layout.
    // NOTE: this whole function is the body of a template literal. NO BACKTICKS --
    // this exact mistake has now cost three debugging rounds in this repo.
    planCanvasCrop: ['panCanvas', 'xsCanvas'].map((id) => {
      const cv = document.getElementById(id);
      if (!cv) return null;
      const wrap = cv.parentElement;
      if (!wrap || wrap.offsetWidth === 0) return null;
      const r = cv.getBoundingClientRect();
      const w = wrap.getBoundingClientRect();
      if (r.width < 1 || w.width < 1) return null;
      const over = Math.max(r.width - w.width, r.height - w.height);
      return over > 1
        ? id + ' ' + Math.round(r.width) + 'x' + Math.round(r.height)
          + ' clipped by ' + Math.round(w.width) + 'x' + Math.round(w.height)
        : null;
    }).filter(Boolean),
  };
})()`;

// ------------------------------------------------------------- the boot path
// EVERYTHING above sets `DENTISTRY_NO_BOOT = true` and calls `openCase()` directly, so
// `boot()` -> `wireViewer` -> `wireRail` -> `wireSide` -> ... has never run under any
// gate in this repo. That is not a gap in coverage, it is a blind spot with a shape:
// anything that only breaks while WIRING is invisible to all 112 states and fails on the
// first real page load.
//
// It happened. `wireXsOverlay` read `planState()`, which returns null until a case is
// open, threw `Cannot set properties of null` inside `wireViewer`, killed `boot()`, and
// left the deployed app blank at "connecting...". Every offline gate was green.
//
// So: load the page for real, let `boot()` run against a stubbed API, and assert it threw
// nothing and revealed a screen. One state, and it is the cheapest one here.
const BOOT_PROBE = `(async () => {
  // Stubbed AFTER the page has loaded, not injected before it: auth.js runs before
  // app.js and would overwrite an injected DentistryAuth, so boot() would take the
  // sign-in branch and this would measure the wrong path entirely. app.js is loaded with
  // DENTISTRY_NO_BOOT set, so boot() has not run yet and can be called here with the
  // stubs in place.
  const errors = [];
  window.addEventListener('error', (e) => errors.push('error: ' + (e.message || e.type)));
  window.addEventListener('unhandledrejection',
    (e) => errors.push('rejection: ' + String((e.reason && e.reason.message) || e.reason)));
  window.fetch = async (url) => {
    const u = String(url);
    // Shaped from 'api/routes/me.py''s own return. A thin stub here does not fail
    // honestly -- it throws somewhere unrelated ("reading 'limit'") and looks like a
    // product bug.
    const b = u.includes('/me') ? {
        user: { id: 'u', email: 'x@y.z', username: 'x' },
        profile: {}, tenantId: 't',
        workspace: { id: 't', name: 'W', members: 1, role: 'owner',
                     isPersonal: true, personalTenantId: 't' },
        plan: { id: 'explorer', name: 'Explorer', isTrial: true, jobQuota: 30 },
        subscription: { status: 'trialing', trialEndsAt: null, currentPeriodEnd: null,
                        cancelAtPeriodEnd: false },
        usage: { used: 0, limit: 30, basis: 'trial' },
        billingEnabled: false }
      : u.includes('/workspaces') ? { workspaces: [{ id: 't', name: 'W', kind: 'personal', role: 'owner' }] }
      : u.includes('/members') ? { members: [], invites: [] }
      : u.includes('/system') ? { state: 'idle', queue: { depth: 0 }, gpu: {} }
      : u.includes('/structures') ? { count: 47, groups: [] }
      : u.includes('/implants') ? { platforms: [], lengths: [], diameter_mm: [],
                                    length_mm: [], notice: 'x' }
      : u.includes('/jobs') ? { jobs: [], total: 0 }
      : {};
    return new Response(JSON.stringify(b), { status: 200,
      headers: { 'content-type': 'application/json' } });
  };
  let threw = null;
  try { await boot(); } catch (e) { threw = String((e && e.message) || e); }
  if (state.poll) clearInterval(state.poll);
  await new Promise((r) => setTimeout(r, 250));
  return {
    threw, errors,
    // boot() ends in route(), which reveals a screen. A blank page with no error is
    // the other way this fails, and it is the way it actually failed.
    visible: ['home', 'workspace', 'settings', 'signinGate'].filter((id) => {
      const e = document.getElementById(id);
      return e && !e.hidden;
    }),
    // wireViewer() is where the plan tab's controls are bound and where the regression
    // that blanked the deployed app lived. If it did not finish, nothing below matters.
    wired: ['railToggle', 'sideToggle', 'xsOverlayBtn', 'xsFitBtn'].filter((id) => {
      const e = document.getElementById(id);
      return !!(e && e.onclick);
    }),
  };
})()`;

// `app.js` captures `const AUTH = window.DentistryAuth` AT LOAD, and `auth.js` assigns
// that object before `app.js` runs -- so replacing it from the probe afterwards changes
// nothing and `boot()` takes the sign-in branch. This intercepts the assignment instead:
// whatever auth.js sets is kept, with `init` and the token wrapped so the boot path
// believes it is signed in. Everything else about auth stays real.
const AUTH_WRAP = `(() => {
  const USER = { sub: 'u', email: 'x@y.z', username: 'x' };
  let held = null;
  Object.defineProperty(window, 'DentistryAuth', {
    configurable: true,
    get() { return held; },
    set(v) {
      held = v ? Object.assign({}, v, {
        init: async () => USER,
        isSignedIn: () => true,
        profile: () => USER,
        token: async () => 't',
      }) : v;
    },
  });
})()`;

// PROVEN non-vacuous by reintroducing the real regression -- `wireXsOverlay` writing to
// `planState()`, which is null until a case is open. Three of these fire on it:
//   boot: boot() threw -> Cannot set properties of null (setting 'xsOverlay')
//   boot: boot() revealed [], not the case list
//   boot: wireViewer did not bind xsOverlayBtn, xsFitBtn
// It is not in the `--prove` table because that table mutates FIXTURES and this is a
// source defect; the proof is the paragraph above and it was run.
async function bootCheck(c, sessionId, port) {
  const { identifier } = await c.send('Page.addScriptToEvaluateOnNewDocument',
    { source: AUTH_WRAP }, sessionId);
  const loaded = c.once('Page.loadEventFired');
  await c.send('Page.navigate', { url: `http://127.0.0.1:${port}/index.html` }, sessionId);
  await loaded;
  const { result, exceptionDetails } = await c.send('Runtime.evaluate',
    { expression: BOOT_PROBE, awaitPromise: true, returnByValue: true }, sessionId);
  states += 1;
  if (exceptionDetails) {
    const ex = exceptionDetails.exception || {};
    fail(`boot: the probe threw -> ${ex.description || ex.value || exceptionDetails.text}`);
    await c.send('Page.removeScriptToEvaluateOnNewDocument', { identifier }, sessionId);
    return;
  }
  await c.send('Page.removeScriptToEvaluateOnNewDocument', { identifier }, sessionId);
  const r = result.value || {};
  if (r.threw) fail(`boot: boot() threw -> ${r.threw}`);
  if ((r.errors || []).length) {
    fail(`boot: the boot path raised -> ${r.errors.slice(0, 3).join(' ; ')}`);
  }
  if (!(r.visible || []).includes('home')) {
    fail(`boot: boot() revealed ${JSON.stringify(r.visible)}, not the case list `
         + '-- a blank page with no error is exactly how this failed in production');
  }
  const WANT = ['railToggle', 'sideToggle', 'xsOverlayBtn', 'xsFitBtn'];
  const missing = WANT.filter((k) => !(r.wired || []).includes(k));
  if (missing.length) fail(`boot: wireViewer did not bind ${missing.join(', ')}`);
}

// ------------------------------------------------------------------- runner
let failures = 0; let states = 0;
const fail = (m) => { console.log(`  FAIL  ${m}`); failures += 1; };

async function run(breakage) {
  const { srv, port } = await serve(WEB);
  const profile = mkdtempSync(path.join(tmpdir(), 'checkrail-'));
  const dbg = 9500 + Math.floor(Math.random() * 400);
  const chrome = spawn('google-chrome', [
    '--headless=new', `--remote-debugging-port=${dbg}`, `--user-data-dir=${profile}`,
    '--no-first-run', '--no-default-browser-check', '--disable-gpu',
    '--disable-dev-shm-usage', '--no-sandbox', 'about:blank',
  ], { stdio: 'ignore' });

  const names = readdirSync(FIX).filter((f) => f.endsWith('.json')).map((f) => f.replace('.json', ''));
  try {
    const c = await cdp(dbg);
    const { targetId } = await c.send('Target.createTarget', { url: 'about:blank' });
    const { sessionId } = await c.send('Target.attachToTarget', { targetId, flatten: true });
    await c.send('Page.enable', {}, sessionId);
    await c.send('Runtime.enable', {}, sessionId);
    await c.send('Page.addScriptToEvaluateOnNewDocument',
      { source: 'window.DENTISTRY_NO_BOOT = true;' }, sessionId);

    // The boot path first: if it is broken, nothing below means anything to a user.
    await c.send('Emulation.setDeviceMetricsOverride',
      { width: 1470, height: 900, deviceScaleFactor: 1, mobile: false }, sessionId);
    await bootCheck(c, sessionId, port);

    for (const name of names) {
      let fixture = JSON.parse(readFileSync(path.join(FIX, `${name}.json`), 'utf8'));
      // A per-fixture clone so a --prove break can mutate the ARCH MANIFEST in place
      // without leaking into the next fixture. The plan tab's readouts come from this
      // document, not from the report, so a break confined to the report can never
      // exercise them.
      const arch = structuredClone(ARCH);
      const measure = structuredClone(MEASURE);
      if (breakage) fixture = breakage(name, fixture, arch, measure);
      const want = EXPECT[name] || {};
      // Height is only varied on the plan fixture: it is the only one whose layout is
      // height-bound, and doubling every other fixture's state count buys nothing.
      const heights = want.plan === 1 ? HEIGHTS : [HEIGHTS[0]];
      for (const w of WIDTHS) {
       for (const h of heights) {
        for (const fold of [false, true]) {
          await c.send('Emulation.setDeviceMetricsOverride',
            { width: w, height: h, deviceScaleFactor: 1, mobile: false }, sessionId);
          const loaded = c.once('Page.loadEventFired');
          await c.send('Page.navigate', { url: `http://127.0.0.1:${port}/index.html` }, sessionId);
          await loaded;
          const { result, exceptionDetails } = await c.send('Runtime.evaluate',
            { expression: PROBE(fixture, fold, arch, measure), awaitPromise: true, returnByValue: true }, sessionId);
          if (exceptionDetails) {
            const ex = exceptionDetails.exception || {};
            fail(`${name} @${w}: page threw -> ${ex.description || ex.value || exceptionDetails.text}`);
            continue;
          }
          const r = result.value;
          states += 1;
          const at = `${name} @${w}x${h}${fold ? ' folded' : ''}`;

          if (want.dice === 0 && r.dice !== 0) fail(`${at}: ${r.dice} dice cell(s), expected none`);
          if (want.dice === '>0' && r.dice === 0) fail(`${at}: no dice cells on an accuracy fixture`);
          if (want.plan != null && r.plan !== want.plan) fail(`${at}: ${r.plan} plan tab(s), expected ${want.plan}`);
          if (want.accuracy != null && r.accuracy !== want.accuracy) fail(`${at}: accuracy card ${r.accuracy}, expected ${want.accuracy}`);
          if (r.rows === 0) fail(`${at}: the structure rail rendered no rows at all`);
          if (want.plan === 1) {
            if (!r.implantPanel) fail(`${at}: the plan tab opened but the implant panel is empty`);
            if (r.jawDisabled !== 1) fail(`${at}: ${r.jawDisabled} disabled jaw tab(s), expected 1 (the refused maxilla)`);
            // The probe places two implants from the FDI chart. If placement itself
            // regresses, every assertion below is vacuous and this is the only thing
            // that says so.
            if (r.implantsPlaced !== 2) fail(`${at}: placed ${r.implantsPlaced} implant(s) from the chart, expected 2`);
            // The outlines must actually DRAW. `drawContourSlice` takes its scale as an
            // argument precisely because the tile view is in backing-store pixels and
            // the plan canvas is in image pixels; getting that backwards puts every
            // contour at 2x and off the picture, which looks like a data bug.
            if (r.contoursDrawn === 0) fail(`${at}: the section overlay drew no structures at all`);
            if (r.contoursDrawn > 0 && !r.contoursInside) fail(`${at}: a drawn contour lies outside the section picture -> ${r.contourBounds}`);
            if (r.impHeights.length !== 2) fail(`${at}: ${r.impHeights.length} implant card(s) in the DOM, expected 2`);
            // The live defect this exists for: one implant rendered a 1118 px card and
            // 65% of the sidebar was unreachable. A ceiling, not a target.
            for (const px of r.impHeights) {
              if (px > IMP_CARD_MAX_PX) fail(`${at}: an implant card is ${px} px tall, over the ${IMP_CARD_MAX_PX} px ceiling`);
            }
            for (const n of r.impChars) {
              if (n > IMP_CARD_MAX_CHARS) fail(`${at}: an implant card carries ${n} characters, over the ${IMP_CARD_MAX_CHARS} ceiling`);
            }
            // The fixture deliberately contains a `no_verdict`. If the panel renders no
            // verdict words at all, or renders the ungraded one as if it were graded,
            // the compact card is lying about the one state that matters most.
            const words = (r.verdictWords || []).join(' | ').toLowerCase();
            if (!r.verdictWords || !r.verdictWords.length) fail(`${at}: the implant panel shows no verdict at all`);
            else if (!/not graded|no verdict/.test(words)) fail(`${at}: the fixture carries a no_verdict and the panel never says so -> ${words.slice(0, 160)}`);
            // The pictures must actually paint. `planCanvasCrop` only asks whether the
            // canvas overflows its wrap; a canvas that fits and paints nothing passes it.
            for (const q of r.paint || []) {
              if (q.paintedW < 8 || q.paintedH < 8) fail(`${at}: ${q.id} painted ${q.paintedW}x${q.paintedH} -- the picture did not render`);
            }
          }
          if (want.plan === 0 && r.implantPanel) fail(`${at}: an implant panel on a job with no planning pack`);
          // openCase must fail ONLY for the known reason. See the probe.
          if (r.openCaseError && !EXPECTED_MOUNT_FAILURE.test(r.openCaseError)) {
            fail(`${at}: openCase failed for an unexpected reason -> ${r.openCaseError}`);
          }
          if (BAD_TOKENS.test(r.text)) fail(`${at}: bad token in rail text -> ${(r.text.match(BAD_TOKENS) || [])[0]}`);
          // The measurement surface carries every millimetre a clinician acts on, and
          // was previously checked only for absolute HU. A clearance that renders
          // "undefined mm" is worse than one that renders a forbidden unit.
          if (BAD_TOKENS.test(r.measurementText)) fail(`${at}: bad token in the measurement surface -> ${(r.measurementText.match(BAD_TOKENS) || [])[0]}`);
          if (BAD_TOKENS.test(r.chromeText)) fail(`${at}: bad token in a viewer readout -> ${(r.chromeText.match(BAD_TOKENS) || [])[0]}`);
          if ((r.planCanvasCrop || []).length) fail(`${at}: a plan canvas is cropped by its wrap -> ${r.planCanvasCrop.join('; ')}`);
          // A throw anywhere in a paint path. selectXs's .catch used to swallow these
          // and relabel them as a load failure, and the harness printed ALL PASS.
          if ((r.pageErrors || []).length) fail(`${at}: the page raised -> ${r.pageErrors.slice(0, 2).join(' ; ')}`);
          if (FORBIDDEN_ANYWHERE.test(r.text)) fail(`${at}: bone-quality claim in rail -> ${(r.text.match(FORBIDDEN_ANYWHERE) || [])[0]}`);
          if (FORBIDDEN_IN_MEASUREMENT.test(r.measurementText)) fail(`${at}: absolute HU in the measurement surface -> ${(r.measurementText.match(FORBIDDEN_IN_MEASUREMENT) || [])[0]}`);
          if (!REQUIRED_DISCLAIMER.test(r.allText)) fail(`${at}: the "not calibrated" grey-value disclaimer is missing from the rail`);
          if (r.overflow.length) fail(`${at}: horizontal overflow -> ${r.overflow.join(' ')}`);
          if (r.bodyOverflowX) fail(`${at}: the page itself scrolls horizontally`);
        }
       }
      }
    }
    c.close();
  } finally {
    chrome.kill('SIGKILL'); srv.close();
    await new Promise((r) => setTimeout(r, 300));
    try { rmSync(profile, { recursive: true, force: true }); } catch { /* chrome still exiting */ }
  }
}

// --------------------------------------------------------------------- main
const mode = process.argv[2];
if (mode === '--selftest') {
  // The JS half of the coordinate map, against the same vectors Python asserts.
  const { srv, port } = await serve(WEB);
  const profile = mkdtempSync(path.join(tmpdir(), 'selftest-'));
  const dbg = 9900 + Math.floor(Math.random() * 90);
  const chrome = spawn('google-chrome', [
    '--headless=new', `--remote-debugging-port=${dbg}`, `--user-data-dir=${profile}`,
    '--no-first-run', '--no-default-browser-check', '--disable-gpu',
    '--disable-dev-shm-usage', '--no-sandbox', 'about:blank'], { stdio: 'ignore' });
  try {
    const c = await cdp(dbg);
    const { targetId } = await c.send('Target.createTarget', { url: 'about:blank' });
    const { sessionId } = await c.send('Target.attachToTarget', { targetId, flatten: true });
    await c.send('Page.enable', {}, sessionId);
    await c.send('Runtime.enable', {}, sessionId);
    const loaded = c.once('Page.loadEventFired');
    await c.send('Page.navigate', { url: `http://127.0.0.1:${port}/selftest.html` }, sessionId);
    await loaded;
    const { result } = await c.send('Runtime.evaluate', {
      expression: `(async () => { for (let i = 0; i < 60 && !window.__SELFTEST__; i++)`
        + ` await new Promise(r => setTimeout(r, 100));`
        + ` return { r: window.__SELFTEST__ || null, html: document.getElementById('out').innerText }; })()`,
      awaitPromise: true, returnByValue: true }, sessionId);
    const v = result.value;
    console.log(v.html);
    c.close();
    process.exitCode = (v.r && v.r.failures === 0) ? 0 : 1;
  } finally {
    chrome.kill('SIGKILL'); srv.close();
    await new Promise((r) => setTimeout(r, 300));
    try { rmSync(profile, { recursive: true, force: true }); } catch { /* exiting */ }
  }
} else if (mode === '--prove') {
  // Each entry breaks exactly one thing and must produce at least one FAIL.
  const BREAKS = {
    'a NaN in a metric': (n, f) => {
      if (f.accuracy) f.accuracy.aggregate.mean_dice = 0 / 0;
      else if (f.quality) f.quality.volumes_cm3 = Object.fromEntries(
        Object.keys(f.quality.volumes_cm3).map((k) => [k, 0 / 0]));
      return f;
    },
    'a forbidden Hounsfield claim in copy': (n, f) => {
      const st = f.structures?.[0]?.structures?.[0];
      if (st) st.name = `${st.name} (D2 bone, 850 HU)`;
      return f;
    },
    'the plan tab gating': (n, f) => {
      if (!f.planning) f.planning = { jaws: { mandible: { ok: true } } };
      return f;
    },
    'the accuracy card gating': (n, f) => {
      if (!f.accuracy) {
        f.accuracy = { aggregate: { mean_dice: 0.9, classes_scored: 3 },
                       structures: [], protocol: {}, reference: {} };
      }
      return f;
    },
    // Proves the openCase assertion is not vacuous: the rail's structure list walks
    // report.structures, so a malformed group makes a render function throw, which the
    // old bare catch would have swallowed into a clean ALL PASS.
    'a render function throwing inside openCase': (n, f) => {
      f.structures = [{ group: 'Jaws', structures: 'not-an-array' }];
      return f;
    },
    // Bug 2's exact class, in a readout that lives OUTSIDE the rail: drop a field the
    // manifest is supposed to publish and #xsLabel renders "cross-section 1 of
    // undefined". Nothing caught this until chromeText existed -- worker/preview.py
    // shipped without total_slices and #sliceLabel read "/ undefined" for days.
    'a manifest field a viewer readout depends on': (n, f, arch) => {
      for (const j of Object.values(arch.jaws || {})) {
        if (j && j.cross_sections) delete j.cross_sections.count;
      }
      return f;
    },
    // The panel is only compact while the prose stays behind its disclosures. Forcing
    // every row open is what the old panel effectively did, and it is what the height
    // and character ceilings exist to catch.
    'the per-implant card growing back': (n, f, arch, measure) => {
      (measure.implants || []).forEach((imp) => {
        ['verdict', 'accessory_canal_verdict', 'tooth_verdict'].forEach((k) => {
          if (imp[k]) imp[k].level = 'no_verdict';       // force-open, every row
        });
      });
      return f;
    },
    // The state that must never read as "clear". If the panel stops SAYING "not
    // graded", a refusal is indistinguishable from a pass at a glance.
    'an ungraded verdict rendered as a graded one': (n, f, arch, measure) => {
      (measure.implants || []).forEach((imp) => {
        ['verdict', 'accessory_canal_verdict', 'tooth_verdict'].forEach((k) => {
          if (imp[k] && imp[k].level === 'no_verdict') imp[k].level = 'clear';
        });
      });
      (measure.implants || []).forEach((imp) => {
        (imp.tooth || {}).caveats = [];
      });
      return f;
    },
    // The pictures. A section that does not paint is the failure the whole plan tab is
    // made of, and until the fixture had real images nothing could see it.
    'the cross-section failing to paint': (n, f, arch) => {
      arch.__breakImages = true;
      return f;
    },
  };
  let proven = 0;
  for (const [label, fn] of Object.entries(BREAKS)) {
    failures = 0; states = 0;
    console.log(`\n### breaking: ${label}`);
    await run(fn);
    if (failures > 0) { console.log(`  -> CAUGHT (${failures} failure(s) over ${states} states)`); proven += 1; }
    else console.log('  -> *** NOT CAUGHT: this assertion is vacuous ***');
  }
  console.log(`\n${proven}/${Object.keys(BREAKS).length} assertions proven non-vacuous`);
  process.exit(proven === Object.keys(BREAKS).length ? 0 : 1);
} else {
  await run(null);
  console.log(`\n${failures ? `FAILURES: ${failures}` : 'ALL PASS'} over ${states} measured states`);
  process.exit(failures ? 1 : 0);
}
