/* Emit the landing page's implant geometry by SLICING THE SHIPPED VIEWER, not porting it.
 *
 * `viewer/src/implants.js` is the one place this codebase draws a dental fixture, and it is
 * verified in-tree against Python by `viewer/check-equivalence.mjs` -- the drawn screw is
 * asserted strictly inside the measured capsule, crest touching to 2e-8 mm. A hand port for
 * the landing page would be a second, independently-wrong copy of the one thing this
 * repository insists on having only one of, and it would rot the first time the thread
 * profile changed.
 *
 * So the landing runs the real code. The file's top half -- constants plus the four pure
 * geometry functions -- touches no vtk API; the vtk-dependent half begins at the `arch
 * frame` banner. This slices to that banner, drops the five vtk imports, strips `export`,
 * and re-exports what the hero needs. Same technique as ~/brand/geometry/screw-export.mjs,
 * which feeds the VTK brand renders. Two consumers, one rule.
 *
 * The grading thresholds come from Python the same way. Retyping 2.00 / 0.46 / 0.50 into a
 * marketing page is exactly the class of mistake that put a hand-typed 0.8887 into a
 * delivered film while the app said 0.8965.
 *
 *   node scripts/bake_landing_geometry.mjs            write the modules + update the pointer
 *   node scripts/bake_landing_geometry.mjs --check    exit 1 if anything is stale
 *
 * IT LIVES IN scripts/ AND NOT IN landing/ for a boring but load-bearing reason:
 * `Dockerfile.landing` does `COPY landing/ /usr/share/nginx/html/`, so anything under
 * landing/ is PUBLISHED. `.dockerignore` already excludes scripts/.
 *
 * OUTPUT FILENAMES CARRY A CONTENT HASH, and that is not tidiness. `/assets/` is served
 * `expires 1y; Cache-Control: immutable` (docker/landing-nginx.conf), and a static
 * `import ... from "./screw-geometry.js"` inside `hero3d.js?v=N` does NOT inherit the query
 * string -- the browser fetches the bare URL and a returning visitor keeps last month's
 * geometry for a year, silently. So the names are hashed and the hero reaches them through
 * `arch.assets.json`, the one stable URL fetched with `cache: "no-cache"`. That is the
 * mechanism the GLB already uses; this just puts two more files behind it.
 */
import { readFileSync, writeFileSync, readdirSync, unlinkSync } from 'node:fs';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC = path.join(ROOT, 'viewer/src/implants.js');
const SAFETY_SRC = path.join(ROOT, 'dentistry/plan_safety.py');
const OUTDIR = path.join(ROOT, 'landing/assets');
const POINTER = path.join(OUTDIR, 'arch.assets.json');

// The boundary is a banner comment rather than a line number, so a change ABOVE it does not
// silently move the cut. ~/brand/geometry/screw-export.mjs hardcodes `UPTO = 616` and will
// mis-slice the day someone adds a line; it should adopt this.
const BANNER = '/* ------------------------------------------------------------------- arch frame */';

// Everything the hero needs to draw what the app draws: the two mesh builders, the capsule's
// radius law, the tessellations, the titanium body colour, the graded shell radii and the
// verdict palette. None of it is retyped on the landing side.
const EXPORTS = ['screwLocal', 'capsuleLocal', 'envelopeRadius',
                 'SCREW_AZIMUTH', 'N_AZIMUTH', 'DOME_RINGS',
                 'SHELL_AZIMUTH', 'SHELL_DOME_RINGS',
                 'BODY_RGB', 'SHELL_MARGIN_MM', 'VERDICT_RGB', 'NEUTRAL_RGB'];

const SAFETY_NAMES = ['SAFETY_MARGIN_MM', 'TIGHT_BAND_MM', 'MODEL_INWARD_P95_MM',
                      'MODEL_INWARD_WORST_MM', 'MODEL_INWARD_MEDIAN_MM',
                      'ADJACENT_MARGIN_MM', 'INTER_IMPLANT_MARGIN_MM'];

const sha8 = (s) => createHash('sha256').update(s).digest('hex').slice(0, 8);

function buildGeometry() {
  const src = readFileSync(SRC, 'utf8');
  const lines = src.split('\n');
  const hits = lines.filter((l) => l.trimEnd() === BANNER).length;
  if (hits !== 1) throw new Error(`the boundary banner appears ${hits} times in ${SRC} -- pick a new one deliberately`);
  const cut = lines.findIndex((l) => l.trimEnd() === BANNER);

  const slice = lines.slice(0, cut).join('\n');
  const sha = createHash('sha256').update(slice).digest('hex');
  const body = slice.split('\n')
    .filter((l) => !/^import\s/.test(l))
    .map((l) => l.replace(/^export\s+/, ''))
    .join('\n');

  const header = [
    '/* GENERATED by scripts/bake_landing_geometry.mjs from viewer/src/implants.js -- DO NOT EDIT.',
    ' *',
    ' * This is the SHIPPED implant geometry, sliced out of the viewer above its first use of',
    ' * vtk.js. Edit viewer/src/implants.js and re-run the baker; never edit this file.',
    ' * `node scripts/bake_landing_geometry.mjs --check` fails when the two disagree.',
    ' *',
    ` * source lines : 1..${cut}`,
    ` * sha256(slice): ${sha}`,
    ' *',
    ' * Three of the functions below reference vtk.js identifiers the slice does not define',
    ' * (attach/teardown/setImplantArch). They are never called here, and JS does not resolve a',
    ' * free identifier until the call, so evaluating this module is safe. They are kept rather',
    ' * than surgically removed because a name-based excision is one refactor away from cutting',
    ' * the wrong thing.',
    ' */',
    '',
  ].join('\n');

  const text = header + body + `\nexport {\n  ${EXPORTS.join(',\n  ')},\n};\n`;
  return { text, sha, cut, name: `screw-geometry.${sha8(text)}.js` };
}

function buildSafety() {
  const src = readFileSync(SAFETY_SRC, 'utf8');
  const vals = {};
  for (const name of SAFETY_NAMES) {
    // Anchored at column 0 so a value mentioned inside a docstring or a comment cannot win
    // over the declaration.
    const m = src.match(new RegExp(`^${name}\\s*=\\s*([0-9]+(?:\\.[0-9]+)?)`, 'm'));
    if (!m) throw new Error(`${name} not found in ${SAFETY_SRC}`);
    vals[name] = Number(m[1]);
  }
  // A cross-check that costs nothing and would catch a drift between the two files: the
  // mandible shell radius IS the margin plus the canal's inward p95.
  const shell = vals.SAFETY_MARGIN_MM + vals.MODEL_INWARD_P95_MM;
  if (Math.abs(shell - 2.46) > 1e-9) {
    throw new Error(`margin + p95 = ${shell}, but implants.js draws the mandible shell at ` +
                    '2.46 mm. One of the two moved; reconcile them deliberately.');
  }
  const text = [
    '/* GENERATED by scripts/bake_landing_geometry.mjs from dentistry/plan_safety.py -- DO NOT EDIT.',
    ' *',
    ' * The grading thresholds the hero reads a clearance against, taken from the module that',
    ' * grades them for real. `--check` fails on drift.',
    ' */',
    '',
    ...SAFETY_NAMES.map((n) => `export const ${n} = ${vals[n].toFixed(2)};`),
    '',
  ].join('\n');
  return { text, vals, name: `safety-constants.${sha8(text)}.js` };
}

const geom = buildGeometry();
const safety = buildSafety();
const pointer = JSON.parse(readFileSync(POINTER, 'utf8'));
const wanted = { ...pointer, screw: geom.name, safety: safety.name };
const pointerText = JSON.stringify(wanted, null, 2) + '\n';

const read = (f) => { try { return readFileSync(f, 'utf8'); } catch { return null; } };

if (process.argv.includes('--check')) {
  const stale = [];
  if (read(path.join(OUTDIR, geom.name)) !== geom.text) stale.push(geom.name);
  if (read(path.join(OUTDIR, safety.name)) !== safety.text) stale.push(safety.name);
  if (pointer.screw !== geom.name) stale.push(`arch.assets.json:screw (${pointer.screw})`);
  if (pointer.safety !== safety.name) stale.push(`arch.assets.json:safety (${pointer.safety})`);
  if (!stale.length) {
    console.log(`ok  ${geom.name} matches implants.js 1..${geom.cut} (${geom.sha.slice(0, 12)})`);
    console.log(`ok  ${safety.name} matches plan_safety.py ` +
                `(margin ${safety.vals.SAFETY_MARGIN_MM} + p95 ${safety.vals.MODEL_INWARD_P95_MM})`);
    process.exit(0);
  }
  console.error(`STALE: ${stale.join(', ')}`);
  console.error('       run: node scripts/bake_landing_geometry.mjs');
  process.exit(1);
}

writeFileSync(path.join(OUTDIR, geom.name), geom.text);
writeFileSync(path.join(OUTDIR, safety.name), safety.text);
writeFileSync(POINTER, pointerText);

// Sweep old hashes. They are unreachable the moment the pointer moves, and leaving them
// behind grows the published image by a copy per rebuild.
let swept = 0;
for (const f of readdirSync(OUTDIR)) {
  if (!/^(screw-geometry|safety-constants)\.[0-9a-f]{8}\.js$/.test(f)) continue;
  if (f === geom.name || f === safety.name) continue;
  unlinkSync(path.join(OUTDIR, f));
  swept += 1;
}

console.log(`wrote landing/assets/${geom.name}  (${geom.text.length} B, source 1..${geom.cut}, ${geom.sha.slice(0, 12)})`);
console.log(`wrote landing/assets/${safety.name}  (margin ${safety.vals.SAFETY_MARGIN_MM}, ` +
            `p95 ${safety.vals.MODEL_INWARD_P95_MM}, tight band ${safety.vals.TIGHT_BAND_MM})`);
console.log(`pointer arch.assets.json updated${swept ? `, swept ${swept} stale hash(es)` : ''}`);
