#!/usr/bin/env python
"""Decide which model owns which structure, and refuse to decide when it cannot be known.

This is a decision RECORD, not an automation. It applies the rule that was committed to
before any of these numbers existed, prints the evidence beside the verdict, and emits a
document a `TF3_BOARD` change is expected to cite.

**The rule.** A third-party model takes ownership of a structure only if it wins on
`Dice-GT` **and** on detection error measured over fully-annotated cases, and is not
contradicted externally. Wins under leakage do not count; losses do.

**Why `OWN` is mostly unreachable here, stated plainly rather than worked around.**
TotalSegmentator trained on the public ToothFairy3 release; ToothSeg trained on
ToothFairy2, a SUBSET of it. Our 20-case holdout is a split *we* made out of that same
release, so both have almost certainly seen all 20. Two consequences:

* On this holdout a third-party WIN is uninterpretable and a LOSS is real -- leakage can
  only have helped it, so a model that still loses, loses.
* The detection leg is not measurable at all. Measured over the 20 label files, only
  **three** cases annotate a complete dentition (teeth >= 28 and pulp == teeth):
  F_008, F_041, F_046 -- and all three are leaked for both models.

There is one leak-free comparison available, and only for ToothSeg: the extracted set is
63 F + 417 P + 52 S = 532, and **63 + 417 = 480, exactly ToothFairy2's released training
count**, so the S subset is precisely the ToothFairy3 addition. Our holdout carries 5 of
them. That claim is load-bearing and is printed as an assumption rather than buried.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

# Complete-dentition cases, measured over the holdout labels rather than assumed.
FULLY_ANNOTATED = ("ToothFairy3F_008", "ToothFairy3F_041", "ToothFairy3F_046")
LEAK_FREE_FOR = {"toothseg": "S"}          # the ToothFairy3 addition


def _per_class(run: dict, cases: list) -> dict:
    out: dict = {}
    for cid in cases:
        for s in run["per_case"].get(cid, {}).get("classes", []):
            out.setdefault(s["name"], {})[cid] = s
    return out


def _dice_gt(rows: dict, cases: list):
    vals = [(r.get("dice") if r.get("dice") is not None else 0.0)
            for c in cases if (r := rows.get(c)) and r.get("gt_voxels", 0) > 0]
    return (sum(vals) / len(vals)) if vals else None


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ours", required=True, type=Path)
    ap.add_argument("--challenger", required=True, type=Path, action="append",
                    dest="challengers")
    ap.add_argument("--name", action="append", dest="names", default=None)
    ap.add_argument("--out", type=Path, default=Path("eval/ownership.md"))
    args = ap.parse_args()

    ours = json.loads((args.ours / "metrics.json").read_text())
    names = args.names or [p.name for p in args.challengers]

    lines = [
        "# Structure ownership",
        "",
        "Which model draws which structure, and why. Generated by "
        "`scripts/board_ownership.py`; a `TF3_BOARD` change is expected to cite it.",
        "",
        "## The rule, committed to before these numbers existed",
        "",
        "> A third-party model takes ownership of a structure only if it wins on "
        "`Dice·GT` **and** on detection error over fully-annotated cases, and is not "
        "contradicted externally. Wins under leakage do not count; losses do.",
        "",
        "## Why most verdicts here are not `OWN`",
        "",
        "TotalSegmentator trained on the public ToothFairy3 release and ToothSeg on "
        "ToothFairy2, a subset of it. This 20-case holdout is a split *we* made out of "
        "that same release, so both have almost certainly seen all 20 cases.",
        "",
        "* A third-party **win** here is uninterpretable. A **loss** is real: leakage "
        "could only have helped.",
        "* The detection leg cannot be measured. Only **3 of 20** cases annotate a "
        f"complete dentition ({', '.join(FULLY_ANNOTATED)}) and all three are leaked.",
        "",
        "One leak-free comparison exists, for ToothSeg only: 63 F + 417 P = 480 is "
        "exactly ToothFairy2's released training count, so the 52 `S` cases are the "
        "ToothFairy3 addition. **Verify that against ToothFairy2's published case list "
        "before any verdict rests on it.**",
        "",
    ]

    for path, name in zip(args.challengers, names):
        run = json.loads((path / "metrics.json").read_text())
        shared = sorted(set(ours["per_case"]) & set(run["per_case"]))
        leak_free = [c for c in shared
                     if any(f"ToothFairy3{sub}" in c
                            for k, sub in LEAK_FREE_FOR.items() if k in name.lower())]
        a, b = _per_class(ours, shared), _per_class(run, shared)

        wins, losses, undecided = [], [], []
        for cls in sorted(set(a) | set(b)):
            ga, gb = _dice_gt(a.get(cls, {}), shared), _dice_gt(b.get(cls, {}), shared)
            if ga is None or gb is None:
                continue
            d = gb - ga
            row = (cls, ga, gb, d,
                   _dice_gt(b.get(cls, {}), leak_free) if leak_free else None)
            (wins if d > 0.005 else losses if d < -0.005 else undecided).append(row)

        lines += [f"## {name}", "",
                  f"{len(shared)} shared cases"
                  + (f"; {len(leak_free)} of them leak-free for this model" if leak_free
                     else "; **no leak-free subset for this model** — it trained on "
                          "ToothFairy3 itself"),
                  "",
                  "### REJECT — it loses even with leakage in its favour", ""]
        if losses:
            lines += ["| structure | ours ·GT | theirs ·GT | Δ |", "|---|--:|--:|--:|"]
            for cls, ga, gb, d, _ in sorted(losses, key=lambda r: r[3])[:20]:
                lines.append(f"| {cls} | {ga:.4f} | {gb:.4f} | {d:+.4f} |")
            lines.append("")
            lines.append(f"**{len(losses)} structure(s) rejected.** These are the only "
                         f"decisive results on this holdout.")
        else:
            lines.append("None.")
        lines += ["", "### UNDECIDED — it wins, and the win cannot be believed here", ""]
        if wins:
            lines += ["| structure | ours ·GT | theirs ·GT | Δ | leak-free ·GT |",
                      "|---|--:|--:|--:|--:|"]
            for cls, ga, gb, d, lf in sorted(wins, key=lambda r: -r[3])[:20]:
                lines.append(f"| {cls} | {ga:.4f} | {gb:.4f} | {d:+.4f} | "
                             f"{'—' if lf is None else f'{lf:.4f}'} |")
            lines.append("")
            lines.append(
                "**Not adopted.** A win on data the model trained on is not evidence, and "
                "the detection leg of the rule is not measurable on three leaked cases. "
                "The route to a real verdict is shadow mode — run the model on real "
                "clinical uploads, record what it *would* have drawn, and review the "
                "disagreements — or an external tooth dataset.")
        else:
            lines.append("None.")
        lines += ["", f"*{len(undecided)} structure(s) within ±0.005 and not listed.*", ""]

    lines += ["## Verdict", "",
              "**No third-party model takes ownership of any structure.** The board ships "
              "our own canal specialist and nothing else in `apply` mode; both foreign "
              "models are mountable in `shadow` mode, where they run, record what they "
              "would have drawn, and stamp nothing.", ""]
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))
    print(f"\nwrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
